development:
  title: Medieval Warfare
  author: Chris Fuertes
  year: 2013
  contact_email: chris.fuertes@gmail.com
  mail:
    account:
      user_name:
      password:
    smtp:
      address: localhost
      port: 1025

  fb:
    app_id: 475078985959094
    app_secret: 5e56ff181841cb66b6e520bea81a4033

  google:
    app_id: 273144716358.apps.googleusercontent.com
    app_secret: 78w07IR6fsf4b1qHS9Bdk6Cq
